version: '3.8'

services:
  emr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=emr_user
      - DB_PASSWORD=emr_password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emrdb
    depends_on:
      - postgres
    networks:
      - emr-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: emrdb
      POSTGRES_USER: emr_user
      POSTGRES_PASSWORD: emr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emr-network
    restart: unless-stopped

  emr-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    depends_on:
      - emr-backend
    networks:
      - emr-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  emr-network:
    driver: bridge
