services:
  # PostgreSQL Database for EMR Application
  postgres:
    image: postgres:15-alpine
    container_name: emr-postgres
    environment:
      POSTGRES_DB: emrdb
      POSTGRES_USER: emr_user
      POSTGRES_PASSWORD: emr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emr_user -d emrdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database for Keycloak
  keycloak-postgres:
    image: postgres:15-alpine
    container_name: emr-keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - emr-network
    restart: unless-stopped

  # Keycloak for OAuth2/OIDC - Simplified without health check
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: emr-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-postgres  # Simple dependency without health check
    networks:
      - emr-network
    restart: unless-stopped

  # Spring Boot Backend - Simplified dependency
  emr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emr-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emrdb
      - SPRING_DATASOURCE_USERNAME=emr_user
      - SPRING_DATASOURCE_PASSWORD=emr_password
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/emr
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/emr/protocol/openid-connect/certs
      - APP_CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started  # Just wait for container to start
    networks:
      - emr-network
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak_postgres_data:

networks:
  emr-network:
    driver: bridge