spring:
  application:
    name: emr-system

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:emrdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.healthcare: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: mySecretKey
    expiration: 86400000 # 24 hours

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/emrdb
    username: ${DB_USERNAME:emr_user}
    password: ${DB_PASSWORD:emr_password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  h2:
    console:
      enabled: false

logging:
  level:
    com.healthcare: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
